name: "PHPUnit tests"

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    phpunit:
        name: "PHPUnit tests"

        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                php-version:
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"
                    - "8.1"
                    - "8.2"
                    - "8.3"
                operating-system:
                    - "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 0

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: ${{ matrix.php-version }}

            - name: "Update dependencies with composer"
              uses: ramsey/composer-install@v2

            - name: "Tests"
              run: "vendor/bin/phpunit"
